sudo: required
services:
  - docker

before_install:
  - docker build -t mia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mia/react-test npm test -- --coverage

after_success:
  - docker build -t mia/multi-client ./client
  - docker build -t mia/multi-nginx ./nginx
  - docker build -t mia/multi-server ./server
  - docker build -t mia/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mia/multi-client
  - docker push mia/multi-nginx
  - docker push mia/multi-server
  - docker push mia/multi-worker
